#!bin/bash


echo -e '\033[0;37m BlackList \033[0m'
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '
echo '(Escreva O Nome Aqui)'
echo ' '
echo ' '






























