#!bin/bash
while true; do

clear
figlet '==========π' | lolcat
 figlet "|                  TikTak                       | " | lolcat
figlet '==========π' | lolcat
echo ' '
sleep 2
echo ' '
echo ' '
echo -e "\033[1;32m press any key to continue \033[0m "
echo ' '
echo ' '
read -p "why u so serious?" yn

case $yn in
        * ) echo -e "\033[1;31m Starting...\033[0m" ;

sleep 2

clear

sleep 2

bash file5
                break;;

esac

done
