#!bin/bash
while true; do

clear
figlet '==========π' | lolcat
 figlet "|                  TikTak                         | " | lolcat
figlet '==========π' | lolcat
echo ' '
echo ' '
sleep 2
echo -e " \033[1;32m [01]\033[0m \033[1;33m Consulta CPF\033[0m"   
echo ' '
echo ' '
echo -e " \033[1;32m [02]\033[0m \033[1;33m Grabfy\033[0m"   
echo ' '
echo ' '
echo -e " \033[1;32m [03]\033[0m \033[1;33m Consulta nome\033[0m"   
echo ' '
echo ' '
echo -e " \033[1;32m [04]\033[0m \033[1;33m Consulta CPNJ\033[0m"   
echo ' '
echo ' '
echo -e " \033[1;32m [05]\033[0m \033[1;33m Consulta número\033[0m"   
echo ' '
echo ' '
echo -e " \033[1;32m [06]\033[0m \033[0;33m Descobrir a idade\033[0m"   
echo ' '
echo ' '
echo -e " \033[1;32m [07]\033[0m \033[1;34m Adicinar Nomes Na Black List\033[0m"   
echo ' '
echo ' '
echo -e " \033[1;32m [08]\033[0m \033[1;34m Ver Nomes Da Black List\033[0m"   
echo ' '
echo ' '
echo -e " \033[1;32m [09]\033[0m \033[1;31m Sair do programa\033[0m"   
echo ' '
echo ' '
echo ' '
echo ' '
read -p "Digite a opção:" yn
case $yn in
        [1] ) echo -e "\033[1;31m Shhhhhh, é segredu.\033[0m" ;

sleep 2

clear

sleep 1

termux-open --view https://servicos.receita.fazenda.gov.br/Servicos/CPF/ConsultaSituacao/ConsultaPublica.asp

sleep 1

bash file5
                break;;
           [2] ) echo -e "\033[1;31m Shhhhhh, é segredu.\033[0m" ;

sleep 2

clear

sleep 1

termux-open --view https://grabify.link/


bash file5

               
                break;;
           [3] ) echo -e "\033[1;31m Shhhhhh, é segredu.\033[0m" ;

sleep 2

clear

sleep 1

termux-open --view https://portaldatransparencia.gov.br/pessoa-fisica/busca/lista?pagina=1&tamanhoPagina=10


bash file5


                break;;
           [4] ) echo -e "\033[1;31m Shhhhhh, é segredu.\033[0m" ;

sleep 2

clear

sleep 1

termux-open --view https://solucoes.receita.fazenda.gov.br/Servicos/cnpjreva/cnpjreva_solicitacao.asp

bash file5


                break;;
        [5] ) echo -e "\033[1;31m Shhhhhh, é segredu." ;
sleep 2

clear

sleep 1

termux-open --view https://consultanumero.abrtelecom.com.br/consultanumero/consulta/consultaSituacaoAtualCtg

bash file5

                break;;
        [6] ) echo -e "\033[1;31m Lista Negra ";

sleep 1

clear

bash clr.sh


                break;;
        [7] ) echo -e "\033[1;31m Lista Negra " ;

sleep 1

clear

sleep 1

nano BlackList

bash file5
               break;;
          [8] ) echo -e "\033[1;31m Lista Negra " ;

sleep 1

clear

sleep 1

bash BlackList

sleep 16

bash file5
              break;;
           [9] ) echo 'Bye' ;
                exit;;
        * ) echo -e " \033[1;33m [!]\033[0m \033[5;30m Wrong Option.\033[0m"
esac

sleep 1

clear

done
