#!bin/bash
while true; do

clear
figlet '==========π' | lolcat
 figlet "|                  TikTak                       | " | lolcat
figlet '==========π' | lolcat
echo ' '
sleep 2
echo ' '
echo ' '
echo -e "\033[1;32m press any key to continue \033[0m 
echo ' '
echo ' '
read -p "Digite a opção:" yn

case $yn in
        [1] ) echo -e "\033[1;31m Starting...\033[0m" ;

sleep 2

clear

sleep 2

bash file5
                break;;
       [2] ) echo -e "\033[1;31m by ixz\033[0m" ;

sleep 1

clear

sleep 2

figlet 'o mlhr?' | lolcat

sleep 2

clear

sleep 1

bash file1


                break;;
          [3] )  echo 'Até a próxima, bacana!' ;
                exit;;
        * ) echo -e " \033[1;33m [!]\033[0m \033[5;30m Wrong Option.\033[0m"
esac

sleep 1

clear

done
