#!bin/bash
while true; do

clear

sleep 2

echo -e " \033[1;31m [!]\033[0m \033[1;33m Want start the program?\033[0m"   
echo ' '
echo ' '
echo ' '
echo -e " \033[1;31m [!]\033[0m \033[1;33m Sim ou Não?(s/n)\033[0m"   
read -p " " yn

case $yn in
        [sS] ) echo -e "\033[1;31m Starting Program...\033[0m" ;

sleep 1

clear

sleep 2

pkg update && pkg upgrade

pkg install figlet

pkg install python -y

pip install lolcat

echo 'All Requests Installed!'

sleep 2

clear

bash file1


                break;;
           [nN] ) echo '' ;
                exit;;
        * ) echo -e " \033[1;33m [!]\033[0m \033[5;30m Wrong Option.\033[0m"
esac

sleep 1

clear

done
